apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: orders
  namespace: spark-apps
spec:
  type: Scala
  mode: cluster
  sparkVersion: "3.0.0"
  image: "localhost:5000/spark-k8s/sparkapp:1.0-SNAPSHOT"
  imagePullPolicy: Always
  mainClass: ro.esolutions.sparkapp.OrdersApp
  arguments:
    - "DataTweak9s steps"
  mainApplicationFile: local:///sparkapp.jar
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: "datashare"
      hostPath:
        path: "/datashare"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: "datashare"
        mountPath: "/datashare"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: "datashare"
        mountPath: "/datashare"
